### ISSUE TITLE
Bluetooth wil not work

### ISSUE THREAD

**Issue by CarlosSprekelsen** [maniacx/Lava-R1s-ROMs#1]
Bluetooth does not work with this Rom. Keepts crashing in a loop. Seems an issue with the Kernel.

**Comment by maniacx** [comment]
Oh. I just checked now and it is not working on my device as well.
Unfortunately I thought I uploaded the source but I didn't and my hard drive is wiped.
I will have a look at it oneone if it an easy fix.

Also kindly comment on xda

https://forum.xda-developers.com/t/lava-r1s-no-camera-no-gps-ressurection-remix-rr-n-v5-8-5-nougat-7-1-2.4145507/

Easier for me to track

**Comment by maniacx** [comment]
Seems like I have missed out a file called, libbt-vendor.so in library.
I will add it separately.
